### ISSUE TITLE
File Manager

### ISSUE THREAD

**Issue by CrazeeGhost** [ps4xploit900/esp32s2#1]
Why is the file manager in the admin disabled? Could you consider enabling it?

**Comment by ps4xploit900** [comment]
?? admin.html

Of course it works, it's you who is ignorant.

Check this video:
https://youtu.be/J8dXHorG4sw?si=_icpw-rGbb6zECsg

**Comment by CrazeeGhost** [comment]
Your File manager (as per the video you linked) - 
![image](https://github.com/user-attachments/assets/d9ca1649-5b21-4a38-9fc4-33804667c476)

Other Esp32 Hosts File Manager - 
![image](https://github.com/user-attachments/assets/8efd4b05-0e79-4c91-8a31-41fbf191b71f)

Sincerely,
Ignorant

**Comment by ferboiar** [comment]
[CrazeeGhost](https://github.com/CrazeeGhost) is right, the original file manager has been removed. Stooged, in his project (https://github.com/stooged/ESP32-Server-900u), includes a file manager to view, download, and delete files that your project has overwritten, so that functionality has been lost. 

Updating the GoldHen caused me to make a mistake with the file name and have to reflash the firmware completely because I couldn't simply delete the specific file through the file manager. 

Could you include the original functionality please? :)
